apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bnkr.fullname" . }}
data:
  {{- if .Release.IsInstall }}
  USERPASSWORD: {{ default (randAlphaNum 26) .Values.password | b64enc | quote }}
  {{ else }}
  USERPASSWORD: {{ default (index (lookup "v1" "Secret" .Release.Namespace (include "bnkr.fullname" .)).data "USERPASSWORD") (.Values.password | b64enc | quote) }}
  {{ end }}
  USEREMAIL: {{ default "me@example.com" .Values.useremail | b64enc | quote }}
  {{ if .Values.postgresql.enabled }}
  {{- if .Release.IsInstall }}
  DB_PASSWORD: {{ default (randAlphaNum 26) .Values.postgresql.global.postgresql.auth.password | b64enc | quote }}
  {{ else }}
  DB_PASSWORD: {{ default (index (lookup "v1" "Secret" .Release.Namespace (include "bnkr.fullname" .)).data "DB_PASSWORD") (.Values.postgresql.global.postgresql.auth.password | b64enc | quote) }}
  {{ end }}
  {{ else }}
  {{- if .Release.IsInstall }}
  DB_PASSWORD: {{ default (randAlphaNum 26) .Values.database.password | b64enc | quote }}
  {{ else }}
  DB_PASSWORD: {{ default (index (lookup "v1" "Secret" .Release.Namespace (include "bnkr.fullname" .)).data "DB_PASSWORD") (.Values.database.password | b64enc | quote) }}
  {{ end }}
  {{ end }}
  {{ if .Values.postgresql.enabled }}
  DB_NAME: {{ .Values.postgresql.global.postgresql.auth.database | b64enc | quote }}
  {{ else }}
  DB_NAME: {{ default "bnkr" .Values.database.name | b64enc | quote }}
  {{ end }}
  {{ if .Values.postgresql.enabled }}
  DB_USER: {{ default "bnkr" .Values.postgresql.global.postgresql.auth.username | b64enc | quote }}
  {{ else }}
  DB_USER: {{ default "bnkr" .Values.database.username | b64enc | quote }}
  {{ end }}
